### ISSUE TITLE
Panic on Invalid Input Instead of Returning Error

### ISSUE THREAD

**Issue by twsiyuan** [lnquy/cron#10]
## Description:

I encountered a runtime panic instead of a handled error return when passing an invalid cron expression "1 1 1 x 1" to the `ToDescription` method. The program should return an error according to best practices rather than causing a panic.

## Steps to Reproduce:

Use the following Go code snippet or [Playground](https://go.dev/play/p/qZvInfa_Kaa):

```go
package main

import (
	"fmt"
	"github.com/lnquy/cron"
)

func main() {
	desc, err := cron.NewDescriptor()
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	text, err := desc.ToDescription("1 1 1 x 1", cron.Locale_en)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	fmt.Println(text)
}
```

## Expected Result:
The method ToDescription should return an error indicating that the input is invalid.

## Actual Result:

The program panics with the message:
```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/lnquy/cron.(*ExpressionDescriptor).getMonthDescription.func1({0x4f9b9b?, 0x4f9b9b?})
	/tmp/gopath3485488474/pkg/mod/github.com/lnquy/cron@v1.1.1/cron.go:277 +0x57
github.com/lnquy/cron.getSegmentDescription({0x4f9b9b, 0x1}, {0x0?, 0x0?}, 0xc000121cb8, 0xc000121ca0, 0xc000121c88, 0xc000121c70, {0x535438, 0xc000010120})
	/tmp/gopath3485488474/pkg/mod/github.com/lnquy/cron@v1.1.1/cron.go:490 +0x139
github.com/lnquy/cron.(*ExpressionDescriptor).getMonthDescription(0xc0000164e0?, {0xc000119340, 0x7, 0x7?}, {0x535438, 0xc000010120})
	/tmp/gopath3485488474/pkg/mod/github.com/lnquy/cron@v1.1.1/cron.go:272 +0x169
github.com/lnquy/cron.(*ExpressionDescriptor).ToDescription(0xc0000164e0, {0x4f9b95?, 0x0?}, {0x4f908c, 0x2})
	/tmp/gopath3485488474/pkg/mod/github.com/lnquy/cron@v1.1.1/cron.go:84 +0x1e5
main.main()
	/tmp/sandbox593502589/prog.go:16 +0x46
```

**Comment by JedWalton** [comment]
Kindly, please consider:
https://go.dev/blog/error-handling-and-go
